# Generated by Django 5.1.4 on 2025-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_address_line_1_order_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_total",
            field=models.FloatField(default=0.0),
        ),
    ]
