# Generated by Django 5.1.4 on 2025-01-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="EUR", max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
