# Generated by Django 5.1.4 on 2025-01-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_payment_currency_alter_payment_amount_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order_number",
            field=models.CharField(default="0000000000", max_length=50),
        ),
    ]
