# Generated by Django 5.1.4 on 2025-01-31 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_payment_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
    ]
